# Generated by Django 5.2 on 2025-12-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
