# Generated by Django 5.2 on 2025-12-06 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_sliderimage_description_alter_sliderimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fixed', models.BooleanField(default=False, help_text='Cocher pour garder en tête de menu (top-level figée)')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage parmi les frères")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ecommerce.category')),
            ],
            options={
                'ordering': ('parent__id', 'order', 'name'),
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
