# Generated by Django 5.2 on 2025-12-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-is_fixed', 'order', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='category_thumbs/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Garder visible dans la barre principale'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
