# Generated by Django 5.2 on 2025-12-06 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('heading', models.CharField(blank=True, max_length=120)),
                ('column_type', models.CharField(choices=[('list', 'Liste'), ('brands', 'Marques'), ('cards', 'Cartes')], default='list', max_length=12)),
                ('cards', models.ManyToManyField(blank=True, related_name='menu_cards', to='ecommerce.category')),
                ('items', models.ManyToManyField(blank=True, related_name='menu_items', to='ecommerce.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_columns', to='ecommerce.category')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
