# Generated by Django 5.2 on 2025-12-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_menucolumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucolumn',
            options={'ordering': ('order',), 'verbose_name': 'Colonne de menu', 'verbose_name_plural': 'Colonnes de menu'},
        ),
        migrations.AlterField(
            model_name='menucolumn',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='menu_as_cards', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='menucolumn',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='menu_as_items', to='ecommerce.category'),
        ),
    ]
