# Generated by Django 5.2 on 2025-12-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_menucolumn_options_alter_menucolumn_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucolumn',
            name='cards',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les catégories (ou produits) à afficher en vignettes (cards).', related_name='menu_as_cards', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='menucolumn',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les catégories (niveau 3) à afficher dans cette colonne (list/brands).', related_name='menu_as_items', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='menucolumn',
            name='subcategory',
            field=models.ForeignKey(help_text='La sous-catégorie (niveau 2) à laquelle cette colonne appartient.', on_delete=django.db.models.deletion.CASCADE, related_name='menu_columns', to='ecommerce.category'),
        ),
    ]
