# Generated by Django 5.2 on 2025-12-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_menucolumn_cards_alter_menucolumn_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='ecommerce.category')),
            ],
            options={
                'verbose_name': 'Historique slug catégorie',
                'verbose_name_plural': 'Historique slugs catégories',
                'ordering': ('-created_at',),
            },
        ),
    ]
