# Generated by Django 5.2 on 2025-12-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_categoryslughistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucolumn',
            name='items',
        ),
        migrations.AlterField(
            model_name='menucolumn',
            name='cards',
            field=models.ManyToManyField(blank=True, help_text='(optionnel) catégories à afficher en vignettes (si vous utilisez encore ce champ).', related_name='menu_as_cards', to='ecommerce.category'),
        ),
        migrations.CreateModel(
            name='MenuColumnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_card', models.BooleanField(default=False, help_text="Afficher comme vignette si la colonne est de type 'cards'")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='ecommerce.category')),
                ('menu_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='ecommerce.menucolumn')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('menu_column', 'category')},
            },
        ),
    ]
