# Generated by Django 5.2 on 2025-12-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_menucolumn_items_alter_menucolumn_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Référence interne (SKU).', max_length=64, null=True)),
                ('short_description', models.CharField(blank=True, max_length=400, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('price_current', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('seller', models.CharField(blank=True, max_length=140, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promo_label', models.CharField(blank=True, max_length=60, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='products_extra', to='ecommerce.category')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ecommerce.category')),
            ],
            options={
                'ordering': ('-is_promoted', '-created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sections', to='ecommerce.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sections', to='ecommerce.section')),
            ],
            options={
                'ordering': ('order', '-created_at'),
                'unique_together': {('product', 'section')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(related_name='products', through='ecommerce.ProductSection', to='ecommerce.section'),
        ),
    ]
