# Generated by Django 4.2.29 on 2026-03-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_product_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
