"""
Django settings for oyeo project.

Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path
import dj_database_url

# --------------------------
# BASE
# --------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------
# SECURITY
# --------------------------
# IMPORTANT: ne jamais laisser de SECRET_KEY en dur dans le repo
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-REPLACE_THIS_IN_PROD')
DEBUG = os.getenv("DEBUG", "False") == "True"

# En prod, mettre tes domaines séparés par des virgules dans la variable ALLOWED_HOSTS
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# --------------------------
# APPS
# --------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tes apps
    'ecommerce',
]

# --------------------------
# MIDDLEWARE
# --------------------------
MIDDLEWARE = [
    "ecommerce.middleware.PreSetupMiddleware",  # si nécessaire
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # doit être avant CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------
# URLS & TEMPLATES
# --------------------------
ROOT_URLCONF = 'oyeo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # créer un dossier templates à la racine si besoin
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.context_processors.menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'oyeo.wsgi.application'

# --------------------------
# DATABASE
# --------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)

# --------------------------
# PASSWORD VALIDATION
# --------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# --------------------------
# INTERNATIONALIZATION
# --------------------------
LANGUAGE_CODE = 'fr-fr'
# Si tu veux utiliser l'heure locale du Congo-Brazzaville tu peux mettre 'Africa/Brazzaville'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------
# STATIC FILES
# --------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise pour servir les fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --------------------------
# MEDIA & CLOUDINARY
# --------------------------
# Option 1 (préférée) : CLOUDINARY_URL (format: cloudinary://API_KEY:API_SECRET@CLOUD_NAME)
# Option 2 : variables séparées CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET

CLOUDINARY_URL = os.getenv('CLOUDINARY_URL', None)
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', None)
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', None)
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', None)

# Si Cloudinary est configuré (via CLOUDINARY_URL ou via les 3 variables), on active cloudinary storage.
USE_CLOUDINARY = bool(
    CLOUDINARY_URL or (CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET)
)

if USE_CLOUDINARY:
    # Ajout conditionnel des apps pour éviter d'exiger les libs en dev si non utilisées
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']

    # Configuration Cloudinary (peut rester vide si tu utilises CLOUDINARY_URL)
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME or os.getenv('CLOUDINARY_CLOUD_NAME', None),
        'API_KEY': CLOUDINARY_API_KEY or os.getenv('CLOUDINARY_API_KEY', None),
        'API_SECRET': CLOUDINARY_API_SECRET or os.getenv('CLOUDINARY_API_SECRET', None),
    }

    # Stockage par défaut -> Cloudinary
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

    # MEDIA_URL reste utile pour les chemins dans les templates (Cloudinary renverra des URLs externes)
    MEDIA_URL = '/media/'
    # MEDIA_ROOT n'est pas utilisé en production avec Cloudinary, mais peut rester défini pour dev.
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # Développement local : stockage sur filesystem
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# --------------------------
# DEFAULT AUTO FIELD
# --------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------
# LOGGING (simple)
# --------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler',},
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
}
